version: '3.3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'graphqlize'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'UTC'
    ports:
      - '30306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+00:00' ]
volumes:
  mysql-db:
